apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.google.cloudcrd.weisnix.org
spec:
  group: google.cloudcrd.weisnix.org
  version: v1
  names:
    kind: Project
    singular: project
    plural: projects
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
            region:
              type: string
            zone:
              type: string
            serviceaccountsecret:
              type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instances.google.cloudcrd.weisnix.org
spec:
  group: google.cloudcrd.weisnix.org
  version: v1
  names:
    kind: Instance
    singular: instance
    plural: instances
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            project:
              type: string
            type:
              type: string
            image:
              type: string
            disksize:
              type: integer
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.google.cloudcrd.weisnix.org
spec:
  group: google.cloudcrd.weisnix.org
  version: v1
  names:
    kind: Database
    singular: database
    plural: databases
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            project:
              type: string
            type:
              type: string
